backend = "glx";
vsync = true;
glx-use-copysubbuffer-mesa = true;
xrender-sync = true;
xrender-sync-fence = true;

# corners
rounded-corners = true;
corner-radius = 4;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
];

# blur
blur-method = "dual_kawase";
blur-size = 2;
blur-strength = 2;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = true;
blur-kern = "3x3box";
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'utility'",
  "window_type = 'tooltip'",
];

# shadow
shadow = true;
shadow-radius = 5;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.6;
shadow-color = "#bc99ed";
shadow-exclude = [
  "window_type = 'dock'",
  "window_type = 'menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'popup_menu'",
  "window_type = 'utility'",
  "window_type = 'tooltip'",
  "class_g = 'Polybar'",
  "class_g = 'Rofi'"
]

# opacity
inactive-opacity = 0.95;
active-opacity = 0.95;

# fade effect
fading = true;
fade-delta = 5;
no-fading-openclose = false;