[keyboard]
bindings = [
  { key = "Paste", action = "None" },
  { key = "Copy", action = "None" },
  { key = "L", mods = "Control", action = "None" },
  { key = "L", mods = "Control", mode = "~Vi|~Search", chars = "None" },
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "None" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "None" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "None" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "None" },

  # Vi Mode
  { key = "Space", mods = "Shift|Control", mode = "~Search", action = "None" },
  { key = "Space", mods = "Shift|Control", mode = "Vi|~Search", action = "None" },
  { key = "Escape", mode = "Vi|~Search", action = "None" },
  { key = "I", mode = "Vi|~Search", action = "None" },
  { key = "C", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "Y", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "E", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "G", mode = "Vi|~Search", action = "None" },
  { key = "G", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "B", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "F", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "U", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "D", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "Y", mode = "Vi|~Search", action = "None" },
  { key = "Copy", mode = "Vi|~Search", action = "None" },
  { key = "V", mode = "Vi|~Search", action = "None" },
  { key = "V", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "V", mods = "Control", mode = "Vi|~Search", action = "None" },
  { key = "V", mods = "Alt", mode = "Vi|~Search", action = "None" },
  { key = "Return", mode = "Vi|~Search", action = "None" },
  { key = "K", mode = "Vi|~Search", action = "None" },
  { key = "J", mode = "Vi|~Search", action = "None" },
  { key = "H", mode = "Vi|~Search", action = "None" },
  { key = "L", mode = "Vi|~Search", action = "None" },
  { key = "Up", mode = "Vi|~Search", action = "None" },
  { key = "Down", mode = "Vi|~Search", action = "None" },
  { key = "Left", mode = "Vi|~Search", action = "None" },
  { key = "Right", mode = "Vi|~Search", action = "None" },
  { key = "Key0", mode = "Vi|~Search", action = "None" },
  { key = "Key4", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "Key6", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "H", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "M", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "L", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "B", mode = "Vi|~Search", action = "None" },
  { key = "W", mode = "Vi|~Search", action = "None" },
  { key = "E", mode = "Vi|~Search", action = "None" },
  { key = "B", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "W", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "E", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "Key5", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "Slash", mode = "Vi|~Search", action = "None" },
  { key = "Slash", mods = "Shift", mode = "Vi|~Search", action = "None" },
  { key = "N", mode = "Vi|~Search", action = "None" },
  { key = "N", mods = "Shift", mode = "Vi|~Search", action = "None" },

  # Search Mode
  { key = "Return", mode = "Search|Vi", action = "None" },
  { key = "Escape", mode = "Search", action = "None" },
  { key = "C", mods = "Control", mode = "Search", action = "None" },
  { key = "U", mods = "Control", mode = "Search", action = "None" },
  { key = "W", mods = "Control", mode = "Search", action = "None" },
  { key = "P", mods = "Control", mode = "Search", action = "None" },
  { key = "N", mods = "Control", mode = "Search", action = "None" },
  { key = "Up", mode = "Search", action = "None" },
  { key = "Down", mode = "Search", action = "None" },
  { key = "Return", mode = "Search|~Vi", action = "None" },
  { key = "Return", mods = "Shift", mode = "Search|~Vi", action = "None" },

  # Windows / Linux / macOS
  { key = "V", mods = "Control|Shift", mode = "~Vi", action = "None" },
  { key = "C", mods = "Control|Shift", action = "None" },
  { key = "F", mods = "Control|Shift", mode = "~Search", action = "None" },
  { key = "B", mods = "Control|Shift", mode = "~Search", action = "None" },
  { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "None" },
  { key = "Insert", mods = "Shift", action = "None" },
  { key = "Key0", mods = "Control", action = "None" },
  { key = "Equals", mods = "Control", action = "None" },
  { key = "Plus", mods = "Control", action = "None" },
  { key = "NumpadAdd", mods = "Control", action = "None" },
  { key = "Minus", mods = "Control", action = "None" },
  { key = "NumpadSubtract", mods = "Control", action = "None" },
  { key = "Return", mods = "Alt", action = "None" },
  { key = "K", mods = "Command", mode = "~Vi|~Search", chars = "None" },
  { key = "K", mods = "Command", mode = "~Vi|~Search", action = "None" },
  { key = "Key0", mods = "Command", action = "None" },
  { key = "Equals", mods = "Command", action = "None" },
  { key = "Plus", mods = "Command", action = "None" },
  { key = "NumpadAdd", mods = "Command", action = "None" },
  { key = "Minus", mods = "Command", action = "None" },
  { key = "NumpadSubtract", mods = "Command", action = "None" },
  { key = "V", mods = "Command", action = "None" },
  { key = "C", mods = "Command", action = "None" },
  { key = "C", mods = "Command", mode = "Vi|~Search", action = "None" },
  { key = "H", mods = "Command", action = "None" },
  { key = "H", mods = "Command|Alt", action = "None" },
  { key = "M", mods = "Command", action = "None" },
  { key = "Q", mods = "Command", action = "None" },
  { key = "W", mods = "Command", action = "None" },
  { key = "N", mods = "Command", action = "None" },
  { key = "F", mods = "Command|Control", action = "None" },
  { key = "F", mods = "Command", mode = "~Search", action = "None" },
  { key = "B", mods = "Command", mode = "~Search", action = "None" }
]

